### ISSUE TITLE
对于“电子商务网站用户行为分析及服务推荐”数据导入失败

### ISSUE THREAD

**Issue by LelandYan** [JoyceCoder/Data-Mining-Python#1]
对于“电子商务网站用户行为分析及服务推荐”数据库中的表，data里面的sql文件只是插入的数据，请问你的数据库中的表是怎么建立的呢，如果能给我帮助不尽感谢

**Comment by JoyceCoder** [comment]
非常感谢您的提问。我更新了数据文件。7law.zip中的数据为该本书中自带的数据。
我是使用了可视化的sql软件。Navicat for mysql。在本地数据库中直接导入的7law.sql文件。并没有新建表。您可以再试一下。之前应该是我的错误上传问题。

**Comment by LelandYan** [comment]
不好意思，再次麻烦您，我下载了你的7law.zip文件但是，出现解压错误，好像是文件损坏，是解压软件的问题吗？

**Comment by JoyceCoder** [comment]
那您留下个邮箱，我发给您，这部分数据挺大的，传到github可能有些问题？我也不是很清楚 zzj950916 邮箱zzj950916@buaa.edu.cn 签名由 网易邮箱大师 定制 在2019年04月27日 17:30，LelandYan 写道： 不好意思，再次麻烦您，我下载了你的7law.zip文件但是，出现解压错误，好像是文件损坏，是解压软件的问题吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by JoyceCoder** [comment]
那您留下个邮箱，我发给您，这部分数据挺大的，传到github可能有些问题？我也不是很清楚

**Comment by LelandYan** [comment]
yanleland7gmail.com 谢谢您

**Comment by LelandYan** [comment]
yanleland7@gmail.com ,不好意思少打了一个@

**Comment by LelandYan** [comment]
您好，其实您可以给我发一下建立数据表后的表的结构，都使用的什么的字段等，不用发送数据
